In [68]:
import pandas as pd #Importing Pandas for Data Cleaning
from tkinter import filedialog #Importing Filedialog to choose the Data Source File
import tkinter as tk #GUI of the open file dialog

In [69]:
#File Dialog that allows the user to choose the file
root = tk.Tk()
root.withdraw()
dir = filedialog.askopenfilename()
if dir[-3:].lower() == "csv":
    videogames = pd.read_csv(dir, header=0)
elif dir[-4:].lower() == "xlsx":
    videogames = pd.read_excel(dir, header=0)

In [31]:
#The Excel file after converting it to Dataframe, let's have a look on the first 5 values
videogames.head(5)

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,9/17/2013,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,11/18/2014,1/3/2018
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,10/28/2002,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,9/17/2013,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,11/6/2015,1/14/2018

In [32]:
#Checking the datatypes for the Data we got
videogames.dtypes

img              object
title            object
console          object
genre            object
publisher        object
developer        object
critic_score    float64
total_sales     float64
na_sales        float64
jp_sales        float64
pal_sales       float64
other_sales     float64
release_date     object
last_update      object
dtype: object

In [33]:
#Checking info about the Data we have
videogames.info()

'''
After Checking the results, it seems that we have null values in several columns
That we need to fix so it won't interrupt our calculations
'''

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img           64016 non-null  object
 1   title         64016 non-null  object
 2   console       64016 non-null  object
 3   genre         64016 non-null  object
 4   publisher     64016 non-null  object
 5   developer     63999 non-null  object
 6   critic_score  6678 non-null   float64
 7   total_sales   18922 non-null  float64
 8   na_sales      12637 non-null  float64
 9   jp_sales      6726 non-null   float64
 10  pal_sales     12824 non-null  float64
 11  other_sales   15128 non-null  float64
 12  release_date  56965 non-null  object
 13  last_update   17879 non-null  object
dtypes: float64(6), object(8)
memory usage: 6.8+ MB

"\nAfter Checking the results, it seems that we have null values in several columns\nThat we need to fix so it won't interrupt our calculations\n"

In [34]:
#Checking some Statistical Facts about the data
videogames.describe()

,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales
count,6678.000000,18922.000000,12637.000000,6726.000000,12824.000000,15128.000000
mean,7.220440,0.349113,0.264740,0.102281,0.149472,0.043041
std,1.457066,0.807462,0.494787,0.168811,0.392653,0.126643
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.400000,0.030000,0.050000,0.020000,0.010000,0.000000
50%,7.500000,0.120000,0.120000,0.040000,0.040000,0.010000
75%,8.300000,0.340000,0.280000,0.120000,0.140000,0.030000
max,10.000000,20.320000,9.760000,2.130000,9.850000,3.120000

In [35]:
# Let's see how can we handle the na Values::

# Step 1: Check how many na values we have
videogames.isnull().sum()

#After Checking we found out that the null values exists mostly in:
'''
critic_score    57338
total_sales     45094
na_sales        51379
jp_sales        57290
pal_sales       51192
other_sales     48888
'''
#This will raise errors in calculations when dealing with such things

'\ncritic_score    57338\ntotal_sales     45094\nna_sales        51379\njp_sales        57290\npal_sales       51192\nother_sales     48888\n'

In [70]:
#Step 2: let's delete the common null values between the columns mentions above since we can' eliminate all the nulls or we will literally lose our data

videogames.dropna(subset=["critic_score", "total_sales", "na_sales", "jp_sales", "pal_sales", "other_sales"], how="all", inplace=True)

In [71]:
# Now let's check the data after this simple clean:

videogames.isna().sum()

#we got 4 na values in the developer so we can get rid of that as well

videogames.dropna(subset="developer", inplace= True)

In [72]:
#Now let's have another look
videogames.isna().sum()

img                 0
title               0
console             0
genre               0
publisher           0
developer           0
critic_score    14792
total_sales      2552
na_sales         8835
jp_sales        14744
pal_sales        8649
other_sales      6345
release_date      130
last_update     17083
dtype: int64

In [79]:
#We will now convert the img column to the image url.

videogames["img"] = "https://www.vgchartz.com" + videogames["img"]

#Now let's have another look
videogames.head(5)

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,https://www.vgchartz.com/games/boxart/full_651...,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,9/17/2013,NaN
1,https://www.vgchartz.com/games/boxart/full_556...,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,11/18/2014,1/3/2018
2,https://www.vgchartz.com/games/boxart/827563cc...,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,10/28/2002,NaN
3,https://www.vgchartz.com/games/boxart/full_921...,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,9/17/2013,NaN
4,https://www.vgchartz.com/games/boxart/full_499...,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,11/6/2015,1/14/2018

In [82]:
#Now let's check the duplicates
print(videogames.duplicated().sum()) #We have no duplicate values as it shows Zero
''' videogames.drop_duplicates(inplace=True) '''  #if we had duplicate values we would use that

0

' videogames.drop_duplicates(inplace=True) '

In [83]:
#Last Update Column isn't necessary for me in this particular dataset and also it includes around 17k na values so it won't be accurate in analysis
videogames.drop("last_update", axis=1, inplace=True)

In [84]:
#Let's Check Duplicates once more
videogames.duplicated().sum() #It gives us zero so it's fine and we can now get back to the na values

0

In [87]:
#Now let's see what will we do regarding the Na Values (replace them with mean or 0) so let's have another look at them
videogames.isna().sum()

videogames.describe()

#We could replace the na values with the mean but it won't be good as if a game is 7.2 Score and its sales aren't much, it won't make sense so let's just replace them with zeroes

videogames.fillna(0, inplace=True)

In [88]:
videogames.isna().sum() #Now we have no na values

img             0
title           0
console         0
genre           0
publisher       0
developer       0
critic_score    0
total_sales     0
na_sales        0
jp_sales        0
pal_sales       0
other_sales     0
release_date    0
dtype: int64

In [89]:
#Deleting the total_sales = 0 as if it doesn't have any sales, it won't be that beneficial in the analysis
videogames.drop(videogames[videogames["total_sales"] == 0].index, inplace=True)

In [91]:
#Now let's have a look on the data info to see if it's necessary to do anything to it like changing data
videogames.info() #We can change the datatype of the release date from object to date object by doing the follows:

videogames["release_date"] = pd.to_datetime(videogames["release_date"]) #we convert it to datetime first
videogames["release_date"] = videogames["release_date"].dt.date #then we convert it to date

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17568 entries, 0 to 17569
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img           17568 non-null  object
 1   title         17568 non-null  object
 2   console       17568 non-null  object
 3   genre         17568 non-null  object
 4   publisher     17568 non-null  object
 5   developer     17568 non-null  object
 6   critic_score  17568 non-null  float64
 7   total_sales   17568 non-null  float64
 8   na_sales      17568 non-null  float64
 9   jp_sales      17568 non-null  float64
 10  pal_sales     17568 non-null  float64
 11  other_sales   17568 non-null  float64
 12  release_date  17568 non-null  object
dtypes: float64(6), object(7)
memory usage: 1.9+ MB

In [47]:
#Let's Index the data by the genre to make it more organized 
#You May ask why the genre and not the developer, I will show you why

developer_list = videogames["developer"].unique().tolist()
genre_list = videogames["genre"].unique().tolist()
print(len(developer_list), len(genre_list)) #we can see that we have huge number of developers compared to the genre so we can index them by genre better

2663 20

In [92]:
#Indexing
videogames.set_index("genre", inplace=True)
videogames.head(5) #check the Data

,img,title,console,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date
genre,,,,,,,,,,,,
Action,https://www.vgchartz.com/games/boxart/full_651...,Grand Theft Auto V,PS3,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17
Action,https://www.vgchartz.com/games/boxart/full_556...,Grand Theft Auto V,PS4,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18
Action,https://www.vgchartz.com/games/boxart/827563cc...,Grand Theft Auto: Vice City,PS2,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28
Action,https://www.vgchartz.com/games/boxart/full_921...,Grand Theft Auto V,X360,Rockstar Games,Rockstar North,0.0,15.86,9.06,0.06,5.33,1.42,2013-09-17
Shooter,https://www.vgchartz.com/games/boxart/full_499...,Call of Duty: Black Ops 3,PS4,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06

In [93]:
#Let's now sort by index

videogames.sort_values(by="genre", ascending=True, inplace=True)
videogames.head(10)

,img,title,console,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date
genre,,,,,,,,,,,,
Action,https://www.vgchartz.com/games/boxart/full_651...,Grand Theft Auto V,PS3,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17
Action,https://www.vgchartz.com/games/boxart/full_756...,James Cameron's Avatar: The Game,PSP,Ubisoft,Ubisoft Montreal,3.9,0.61,0.22,0.00,0.25,0.14,2009-12-01
Action,https://www.vgchartz.com/games/boxart/5495494c...,Dragon Ball Z: Buu's Fury,GBA,Atari,Webfoot Technologies,5.9,0.61,0.44,0.00,0.16,0.01,2004-09-14
Action,https://www.vgchartz.com/games/boxart/full_403...,Agents of Mayhem,XOne,Deep Silver,Volition Inc.,0.0,0.11,0.07,0.00,0.03,0.01,2017-08-15
Action,https://www.vgchartz.com/games/boxart/5902631c...,X-Men: The Official Game,DS,Activision,Amaze Entertainment,0.0,0.11,0.10,0.00,0.00,0.01,2006-05-16
Action,https://www.vgchartz.com/games/boxart/322265cc...,The Adventures of Jimmy Neutron Boy Genius: Je...,GC,THQ,Krome Studios,0.0,0.11,0.09,0.00,0.02,0.00,2003-09-16
Action,https://www.vgchartz.com/games/boxart/full_266...,Pokémon Rumble World,3DS,Nintendo,Ambrella,7.0,0.11,0.00,0.09,0.02,0.00,2015-04-08
Action,https://www.vgchartz.com/games/boxart/full_pen...,The Penguins of Madagascar: Dr. Blowhole Retur...,DS,THQ,THQ,0.0,0.11,0.06,0.00,0.03,0.01,2011-09-13
Action,https://www.vgchartz.com/games/boxart/full_nar...,Naruto Shippuden: Naruto vs. Sasuke,DS,Atlus,Takara Tomy,0.0,0.11,0.07,0.03,0.00,0.01,2010-11-16
Action,https://www.vgchartz.com/games/boxart/1955023c...,Hitman Trilogy,PS2,Eidos Interactive,IO Interactive,0.0,0.11,0.05,0.00,0.04,0.01,2007-06-30

In [94]:
#Next Thing we wanna do is that we want to export that to MySQL to perform different type of analysis there
#First we have to reset the index (because it causes an error when importing a text index to MySQL Table, I still don't know how to fix it so I found out it's better to reset it :] )
videogames.reset_index(inplace=True)
videogames.head(5)

,genre,img,title,console,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date
0,Action,https://www.vgchartz.com/games/boxart/full_651...,Grand Theft Auto V,PS3,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17
1,Action,https://www.vgchartz.com/games/boxart/full_756...,James Cameron's Avatar: The Game,PSP,Ubisoft,Ubisoft Montreal,3.9,0.61,0.22,0.00,0.25,0.14,2009-12-01
2,Action,https://www.vgchartz.com/games/boxart/5495494c...,Dragon Ball Z: Buu's Fury,GBA,Atari,Webfoot Technologies,5.9,0.61,0.44,0.00,0.16,0.01,2004-09-14
3,Action,https://www.vgchartz.com/games/boxart/full_403...,Agents of Mayhem,XOne,Deep Silver,Volition Inc.,0.0,0.11,0.07,0.00,0.03,0.01,2017-08-15
4,Action,https://www.vgchartz.com/games/boxart/5902631c...,X-Men: The Official Game,DS,Activision,Amaze Entertainment,0.0,0.11,0.10,0.00,0.00,0.01,2006-05-16

In [95]:
#importing to Database
import mysql
import mysql.connector
from sqlalchemy import create_engine

database_name = input("Please Select the Database Name: \n") #Inserting the desired Database Name

conn = mysql.connector.connect(username="root", password="root", host="localhost", port="3306") #Connecting to MySQL to execute SQL commands

cursor = conn.cursor()


cursor.execute(f"CREATE DATABASE IF NOT EXISTS {database_name};") #Creating Chosen Database if it doesn't exists, if exists, it won't be created

engine = create_engine(f"mysql+pymysql://root:root@localhost:3306/{database_name}?charset=utf8mb4") #Connects pandas to SQL Server

table_name = input("Please Select the Table Name: \n")
if_exists_choice = int(input("Press 1 to append data to the table \nPress 2 to replace data in the table\n"))

try:
    if if_exists_choice ==1:
        if_exists_choice = "append"
    elif if_exists_choice ==2:
        if_exists_choice = "replace"
except ValueError as e:
    print(f"An error occured {e} \nPlease Choose a Valid Number:\n")

videogames.to_sql(name=table_name, con=engine, if_exists=if_exists_choice, index=False) #Transferring Data to the MySQL Table

17568